%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2


imu_topic: "/mavros/imu/data_raw"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"


output_path: "/home/skbt/vins_output"


cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.


body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -8.5063268933498470e-03, 2.4843778197476352e-02,
       9.9965515508482161e-01, 5.4776363357612670e-02,
       -9.9996218291217343e-01, -2.0205805142028410e-03,
       -8.4587233024331909e-03, 7.3744375102029018e-03,
       1.8097370817271585e-03, -9.9968930370353615e-01,
       2.4860026396502199e-02, 6.7683188095158206e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -8.0803810517187102e-03, 2.5182434906503792e-02,
       9.9965021503235763e-01, 5.2592400239643372e-02,
       -9.9996563940611982e-01, -2.0543003687671924e-03,
       -8.0311803058554787e-03, -3.9934908825693741e-02,
       1.8513371301044912e-03, -9.9968076145446294e-01,
       2.5198169152859329e-02, 6.8157161475874931e-02, 0., 0., 0., 1. ]
# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ -8.4803492081095833e-03, -2.0174843978479795e-02,
#        9.9976050099398939e-01, 2.9290236288764079e-02,
#        -9.9994859711684148e-01, 5.7277513379707656e-03,
#        -8.3663605391519069e-03, 3.2684433144254742e-03,
#        -5.5575895286736343e-03, -9.9978006008074316e-01,
#        -2.0222380264855344e-02, 1.2406621357012912e-01, 0., 0., 0., 1. ]
# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ -7.9363771441880449e-03, -2.0192802709063873e-02,
#        9.9976460461279504e-01, 2.7226705130398546e-02,
#        -9.9995302437867162e-01, 5.7237373617385900e-03,
#        -7.8222673542890919e-03, -4.5747095224141394e-02,
#        -5.5644365189435607e-03, -9.9977972051315733e-01,
#        -2.0237279877987291e-02, 1.2340223872995211e-01, 0., 0., 0., 1. ]



#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.05                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/fast/savedfiles/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

